services:
  fastgen:
    image: ghcr.io/j27-aurum/gofast/fastgen:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: fastgen
    ports:
      - "8180:8180"
    volumes:
      - fastgen-data:/data
    environment:
      FASTGEN_LISTEN: ":8180"

  fastproxy:
    profiles:
      - proxy
    image: ghcr.io/j27-aurum/gofast/fastproxy:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: fastproxy
    ports:
      - "8181:8181"
    environment:
      FASTPROXY_LISTEN: ":8181"

volumes:
  fastgen-data:
