package provider

import (
	"sync"
	"time"

	"github.com/j27-aurum/gofast/internal/model"
)

// Lineup is one provider's last-good data held in memory. It is not persisted
// directly: channels/programmes are regenerated by re-parsing the raw upstream
// snapshot on boot; only Meta (fetch time + classifications) is stored.
type Lineup struct {
	Channels       []model.Channel
	Programmes     []model.Programme
	ChannelCount   int
	ProgrammeCount int
	FetchedAt      time.Time
}

// Feed is the runtime state for one provider: its Reader + settings + last-good
// Lineup, guarded by its own RWMutex (written by its refresh goroutine, read by
// HTTP handlers and the aggregator).
type Feed struct {
	reader   Reader
	settings model.ProviderSettings
	mu       sync.RWMutex
	lineup   Lineup
}

func newFeed(reader Reader, settings model.ProviderSettings) *Feed {
	return &Feed{reader: reader, settings: settings}
}

// Channels returns a copy of the current channels.
func (f *Feed) Channels() []model.Channel {
	f.mu.RLock()
	defer f.mu.RUnlock()
	return append([]model.Channel(nil), f.lineup.Channels...)
}

// FetchedAt returns when the current lineup was last fetched (zero if never).
func (f *Feed) FetchedAt() time.Time {
	f.mu.RLock()
	defer f.mu.RUnlock()
	return f.lineup.FetchedAt
}

// ID returns the provider id.
func (f *Feed) ID() model.ProviderID { return f.settings.ID }

// Interval returns the configured refresh interval.
func (f *Feed) Interval() time.Duration { return f.settings.RefreshInterval }

// IsEnabled reports whether the provider is enabled.
func (f *Feed) IsEnabled() bool { return f.settings.IsEnabled() }

// Label returns the display label.
func (f *Feed) Label() string { return f.settings.Label }

// Lineup returns a copy of the current lineup (channels + programmes + meta).
func (f *Feed) Lineup() Lineup {
	f.mu.RLock()
	defer f.mu.RUnlock()
	l := f.lineup
	l.Channels = append([]model.Channel(nil), f.lineup.Channels...)
	l.Programmes = append([]model.Programme(nil), f.lineup.Programmes...)
	return l
}

// Programmes returns a copy of the current programmes.
func (f *Feed) Programmes() []model.Programme {
	f.mu.RLock()
	defer f.mu.RUnlock()
	return append([]model.Programme(nil), f.lineup.Programmes...)
}

// Reader returns the provider's fetch adapter.
func (f *Feed) Reader() Reader { return f.reader }

// Set replaces the last-good lineup (called after a successful refresh cycle).
func (f *Feed) Set(l Lineup) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.lineup = l
}

// Settings returns the effective provider settings.
func (f *Feed) Settings() model.ProviderSettings { return f.settings }
