package provider

import (
	"sync"
	"time"

	"github.com/j27-aurum/gofast/internal/model"
)

// Lineup is one provider's last-good data held in memory. It is not persisted
// directly: channels/programmes are regenerated by re-parsing the raw upstream
// snapshot on boot; only irreproducible Meta (fetch time, classifications, and
// historical synthetic number assignments) is stored.
type Lineup struct {
	Channels                []model.Channel
	Programmes              []model.Programme
	ChannelCount            int
	ProgrammeCount          int
	FetchedAt               time.Time
	SyntheticChannelNumbers ChannelNumberAssignments
}

// Stats is the computed API view of one feed's last-known-good lineup.
type Stats struct {
	FetchedAt          time.Time      `json:"fetched_at"`
	LastAttemptAt      time.Time      `json:"last_attempt_at,omitempty"`
	LastError          string         `json:"last_error,omitempty"`
	LastErrorAt        time.Time      `json:"last_error_at,omitempty"`
	TotalChannels      int            `json:"total_channels"`
	ExportedChannels   int            `json:"exported_channels"`
	ExcludedChannels   int            `json:"excluded_channels"`
	TotalProgrammes    int            `json:"total_programmes"`
	ExportedProgrammes int            `json:"exported_programmes"`
	ByClassification   map[string]int `json:"by_classification"`
	ByGroup            map[string]int `json:"by_group"`
	FilterReasons      map[string]int `json:"filter_reasons"`
	GuideStart         time.Time      `json:"guide_start"`
	GuideEnd           time.Time      `json:"guide_end"`
}

// Status is refresh-attempt state persisted separately from content snapshots.
type Status struct {
	LastAttemptAt time.Time `json:"last_attempt_at,omitempty"`
	LastError     string    `json:"last_error,omitempty"`
	LastErrorAt   time.Time `json:"last_error_at,omitempty"`
}

// Feed is the runtime state for one provider: its Reader + settings + last-good
// Lineup, guarded by its own RWMutex (written by its refresh goroutine, read by
// HTTP handlers and the aggregator).
type Feed struct {
	reader   Reader
	settings model.ProviderSettings
	mu       sync.RWMutex
	lineup   Lineup
	status   Status
}

func newFeed(reader Reader, settings model.ProviderSettings) *Feed {
	return &Feed{reader: reader, settings: settings}
}

// Channels returns a copy of the current channels.
func (f *Feed) Channels() []model.Channel {
	f.mu.RLock()
	defer f.mu.RUnlock()
	return append([]model.Channel(nil), f.lineup.Channels...)
}

// FetchedAt returns when the current lineup was last fetched (zero if never).
func (f *Feed) FetchedAt() time.Time {
	f.mu.RLock()
	defer f.mu.RUnlock()
	return f.lineup.FetchedAt
}

// ID returns the provider id.
func (f *Feed) ID() model.ProviderID { return f.settings.ID }

// Interval returns the configured refresh interval.
func (f *Feed) Interval() time.Duration { return f.settings.RefreshInterval }

// IsEnabled reports whether the provider is enabled.
func (f *Feed) IsEnabled() bool { return f.settings.IsEnabled() }

// Label returns the display label.
func (f *Feed) Label() string { return f.settings.Label }

// Lineup returns a copy of the current lineup (channels + programmes + meta).
func (f *Feed) Lineup() Lineup {
	f.mu.RLock()
	defer f.mu.RUnlock()
	l := f.lineup
	l.Channels = append([]model.Channel(nil), f.lineup.Channels...)
	l.Programmes = append([]model.Programme(nil), f.lineup.Programmes...)
	l.SyntheticChannelNumbers = f.lineup.SyntheticChannelNumbers.Clone()
	return l
}

// Programmes returns a copy of the current programmes.
func (f *Feed) Programmes() []model.Programme {
	f.mu.RLock()
	defer f.mu.RUnlock()
	return append([]model.Programme(nil), f.lineup.Programmes...)
}

// Reader returns the provider's fetch adapter.
func (f *Feed) Reader() Reader { return f.reader }

// Set replaces the last-good lineup (called after a successful refresh cycle).
func (f *Feed) Set(l Lineup) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.lineup = l
}

// SetStatus replaces refresh-attempt state.
func (f *Feed) SetStatus(status Status) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.status = status
}

// Settings returns the effective provider settings.
func (f *Feed) Settings() model.ProviderSettings { return f.settings }

// Stats computes provider metrics from the current lineup and status.
func (f *Feed) Stats() Stats {
	f.mu.RLock()
	defer f.mu.RUnlock()

	stats := Stats{
		FetchedAt:        f.lineup.FetchedAt,
		LastAttemptAt:    f.status.LastAttemptAt,
		LastError:        f.status.LastError,
		LastErrorAt:      f.status.LastErrorAt,
		TotalChannels:    len(f.lineup.Channels),
		ExportedChannels: f.lineup.ChannelCount,
		TotalProgrammes:  len(f.lineup.Programmes),
		ByClassification: make(map[string]int),
		ByGroup:          make(map[string]int),
		FilterReasons:    make(map[string]int),
	}

	exported := make(map[string]struct{}, f.lineup.ChannelCount)
	for _, channel := range f.lineup.Channels {
		classification := string(channel.Classification)
		if classification == "" {
			classification = "UNCLASSIFIED"
		}
		stats.ByClassification[classification]++
		group := channel.Group
		if group == "" {
			group = "(none)"
		}
		stats.ByGroup[group]++
		if channel.Excluded {
			stats.ExcludedChannels++
			if channel.FilterReason != "" {
				stats.FilterReasons[channel.FilterReason]++
			}
		}
		if !channel.Excluded && channel.NormalizedID != "" && channel.StreamURL != "" {
			exported[channel.NormalizedID] = struct{}{}
		}
	}

	for _, programme := range f.lineup.Programmes {
		if programme.Title == "" || !programme.Stop.After(programme.Start) {
			continue
		}
		if _, ok := exported[programme.ChannelID]; !ok {
			continue
		}
		stats.ExportedProgrammes++
		if stats.GuideStart.IsZero() || programme.Start.Before(stats.GuideStart) {
			stats.GuideStart = programme.Start
		}
		if stats.GuideEnd.IsZero() || programme.Stop.After(stats.GuideEnd) {
			stats.GuideEnd = programme.Stop
		}
	}
	return stats
}

// Status returns the current refresh-attempt state.
func (f *Feed) Status() Status {
	f.mu.RLock()
	defer f.mu.RUnlock()
	return f.status
}
